version: 2
jobs:
  build:
    working_directory: ~/ashwin-97/circlenode
    docker:
      - image: circleci/node:4.8.3
      environment:
        TEST_DATABASE_URL: mysql://root@127.0.0.1:3306/mroom?sslmode=disable
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: mroom
        DB_USERNAME: root
        DB_PASSWORD: root
      - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mroom
   
    steps:
      - checkout
      - run:
          name: Waiting for Mysql to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && exit 0 && echo Success
              echo -n -
              sleep 1
            done
            echo Failed waiting for Mysql && exit 1
      - run:
          name: Install Dependencies
          command: npm install && npm install mysql
      - run:
          name: Nodeunit
          command: sudo npm install nodeunit -g
      - run:
          command: nodeunit app.js
